# Generated by Django 3.0.3 on 2020-04-16 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='address2',
            field=models.CharField(default=None, max_length=111),
        ),
    ]
